# Generated by Django 3.2.7 on 2021-09-16 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210916_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditors',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
