# Generated by Django 3.2.7 on 2021-09-16 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditors_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospectus', models.FileField(upload_to='prospectus')),
                ('ipo_date', models.DateField()),
                ('ipo_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo', to='core.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dividends')),
                ('final_dividend', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qualifying_date', models.DateField()),
                ('register_closure', models.DateField()),
                ('ex_dividend_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('agm', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
            ],
        ),
    ]
