# Generated by Django 3.2.7 on 2021-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dividend_ipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='share_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Preference', 'Preference'), ('Exchange Tradeable Funds', 'Exchange Tradeable Funds')], default='Public', max_length=255),
        ),
    ]
