# Generated by Django 3.2.7 on 2021-09-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companyprofile_share_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keypeople',
            name='picture',
            field=models.ImageField(default='person.png', upload_to='key_pople'),
        ),
        migrations.CreateModel(
            name='Solicitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(default='sector.png', upload_to='auditors')),
                ('slug', models.SlugField(default='None', unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ManyToManyField(blank=True, related_name='solicitor', to='core.CompanyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(default='sector.png', upload_to='auditors')),
                ('address', models.CharField(max_length=255)),
                ('company', models.ManyToManyField(blank=True, related_name='registrar', to='core.CompanyProfile')),
            ],
        ),
    ]
