# Generated by Django 3.2.7 on 2021-09-16 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210916_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypeople',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
