# Generated by Django 3.2.7 on 2021-09-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_keypeople_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
