# Generated by Django 3.2.7 on 2021-09-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pressrelease_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='final_dividend',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
