# Generated by Django 3.2.7 on 2021-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dividend_final_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedetail',
            name='financial_period_ends',
            field=models.CharField(default='31st December', max_length=255),
        ),
    ]
