# Generated by Django 3.2.7 on 2021-10-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sharedetail_financial_period_ends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shareholder_name', models.CharField(max_length=255)),
                ('shares_owned', models.PositiveBigIntegerField()),
                ('percentage_holding', models.DecimalField(decimal_places=2, max_digits=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
            ],
        ),
    ]
