# Generated by Django 3.2.7 on 2021-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreport',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='marketreport',
            name='session_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
