# Generated by Django 3.2.7 on 2021-10-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211027_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareprice',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='dividend',
            name='financial_year',
            field=models.IntegerField(default='2020'),
        ),
    ]
