# Generated by Django 3.2.7 on 2021-10-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211027_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='market',
            field=models.ManyToManyField(default='None', related_name='tags', to='core.Market'),
        ),
    ]
