# Generated by Django 3.2.7 on 2021-10-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_companyprofile_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidiary_name', models.CharField(max_length=255)),
                ('ownership_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
            ],
        ),
    ]
