# Generated by Django 4.0.6 on 2022-08-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_opinions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audited', models.BooleanField(default=False)),
                ('net_sales_revenue', models.IntegerField()),
                ('total_operating_revenue', models.IntegerField()),
                ('operating_profit_ebit', models.IntegerField()),
                ('gross_profit_ebitda', models.IntegerField()),
                ('net_profit_loss', models.IntegerField()),
                ('total_asset', models.IntegerField()),
                ('total_equity', models.IntegerField()),
                ('current_asset', models.IntegerField()),
                ('total_cash', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('current_liability', models.IntegerField()),
                ('total_liability', models.IntegerField()),
                ('operating_cash_flow', models.IntegerField()),
                ('investing_cash_flow', models.IntegerField()),
                ('financing_cash_flow', models.IntegerField()),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.auditors')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.report')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.financialperiod')),
            ],
        ),
    ]
