# Generated by Django 4.0.6 on 2022-08-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_financialstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='audited',
        ),
    ]
