# Generated by Django 4.0.6 on 2022-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_financialstatement_audited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='current_asset',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='current_liability',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='financing_cash_flow',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='gross_profit_ebitda',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='inventory',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='investing_cash_flow',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='net_profit_loss',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='net_sales_revenue',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='operating_cash_flow',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='operating_profit_ebit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_asset',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_cash',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_equity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_liability',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_operating_revenue',
            field=models.BigIntegerField(),
        ),
    ]
