# Generated by Django 4.0.5 on 2022-08-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='Title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile'),
        ),
    ]
