# Generated by Django 4.2 on 2023-05-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_title_opinions_title_opinions_commentary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypeople',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Chairman', 'Chairman'), ('Director', 'Director'), ('C.F.O', 'C.F.O')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='report',
            name='period',
        ),
        migrations.AddField(
            model_name='report',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.financialperiod'),
            preserve_default=False,
        ),
    ]
