# Generated by Django 4.2 on 2023-05-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_keypeople_position_remove_report_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypeople',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
