# Generated by Django 4.2 on 2023-05-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auditors_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=255)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditors')),
            ],
        ),
    ]
