# Generated by Django 4.2 on 2023-05-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auditingservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditingservices',
            name='auditor',
        ),
    ]
