# Generated by Django 4.2 on 2023-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auditors_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='auditors',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.auditingservices'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.products'),
        ),
    ]
