# Generated by Django 4.2 on 2023-05-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_products_alter_auditors_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_fv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_fv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('split_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
            ],
        ),
    ]
