# Generated by Django 4.2 on 2023-05-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_products_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='employees',
            field=models.IntegerField(default=0),
        ),
    ]
