# Generated by Django 4.2 on 2023-05-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0047_remove_indice_component'),
        ('core', '0034_companyprofile_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='international.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrar',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='incorporated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
