# Generated by Django 4.2 on 2023-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_registrar_country_registrar_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='business_nature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
