# Generated by Django 4.2 on 2023-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_gcx_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcx_types',
            name='logo',
            field=models.ImageField(default='sector.png', upload_to='commodies'),
        ),
    ]
