# Generated by Django 4.2 on 2023-06-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_gcx_types_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='share_type',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Preference', 'Preference'), ('Depository Shares', 'Depository Shares'), ('Exchange Tradeable Funds', 'Exchange Tradeable Funds')], default='Equity', max_length=255),
        ),
    ]
