# Generated by Django 4.2 on 2023-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_companyprofile_share_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('Equity', 'Equity'), ('Preference', 'Preference'), ('Depository Shares', 'Depository Shares'), ('Exchange Tradeable Funds', 'Exchange Tradeable Funds')], default='Equity', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='share_type',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='share_type',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.sharetype'),
        ),
    ]
