# Generated by Django 4.2 on 2023-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_sharetype_remove_companyprofile_share_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='share_type',
            field=models.ManyToManyField(blank=True, default=1, related_name='tags', to='core.sharetype'),
        ),
    ]
