# Generated by Django 4.2 on 2023-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_sharedetail_company_alter_shareprice_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedetail',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
