# Generated by Django 4.2 on 2023-06-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_agm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agm',
            name='event',
        ),
    ]
