# Generated by Django 4.2 on 2023-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_agm_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='agm',
            name='venue',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
