# Generated by Django 4.2 on 2023-06-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_agm_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economiccalendar',
            name='country',
        ),
        migrations.DeleteModel(
            name='AGM',
        ),
        migrations.DeleteModel(
            name='EconomicCalendar',
        ),
    ]
