# Generated by Django 4.2 on 2023-06-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0051_alter_continent_continent'),
        ('core', '0048_remove_economiccalendar_country_delete_agm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('event', models.CharField(max_length=255)),
                ('actual', models.IntegerField()),
                ('forecast', models.IntegerField()),
                ('previous', models.IntegerField()),
                ('file', models.FileField(upload_to='calendar')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='international.country')),
            ],
        ),
        migrations.CreateModel(
            name='AGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
            ],
        ),
    ]
