# Generated by Django 4.2 on 2023-06-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_economiccalendar_agm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='core.companyprofile'),
        ),
    ]
