# Generated by Django 4.2 on 2023-06-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_financialstatement_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend', to='core.companyprofile'),
        ),
    ]
