# Generated by Django 4.2 on 2023-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_brand_companyprofile_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='segments',
            field=models.ManyToManyField(blank=True, to='core.operatingsegment'),
        ),
    ]
