# Generated by Django 4.2 on 2023-06-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField(default='2022')),
                ('total_deposits', models.IntegerField()),
                ('netAdvances', models.IntegerField()),
                ('netImpairments', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='keypeople',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Chairman', 'Chairman'), ('Director', 'Director'), ('C.F.O', 'C.F.O'), ('Member', 'Member')], max_length=50),
        ),
    ]
