# Generated by Django 4.2 on 2023-06-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_bankhealth_alter_keypeople_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankhealth',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile'),
            preserve_default=False,
        ),
    ]
