# Generated by Django 4.2 on 2023-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_bankhealth_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankhealth',
            name='netAdvances',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bankhealth',
            name='netImpairments',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bankhealth',
            name='total_deposits',
            field=models.BigIntegerField(),
        ),
    ]
