# Generated by Django 4.2.3 on 2023-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_bankhealth_netadvances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('picture', models.ImageField(default='person.png', upload_to='key_pople')),
                ('description', models.TextField()),
                ('birth_date', models.DateField()),
                ('highest_education', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('Chairman', 'Chairman'), ('Director', 'Director'), ('C.F.O', 'C.F.O'), ('Member', 'Member')], max_length=50)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('company', models.ManyToManyField(blank=True, related_name='management', to='core.companyprofile')),
            ],
        ),
    ]
