# Generated by Django 4.2.3 on 2023-07-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('C.F.O', 'C.F.O'), ('C.H.R', 'C.H.R'), ('HEAD OF SALES AND MARKETING', 'HEAD OF SALES AND MARKETING'), ('HEAD OF QUALITY AND REGULATORY AFFAIRS', 'HEAD OF QUALITY AND REGULATORY AFFAIRS'), ('HEAD OF SUPPLY CHAIN', 'HEAD OF SUPPLY CHAIN')], max_length=50),
        ),
    ]
