# Generated by Django 4.2 on 2023-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_bill',
            name='discount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='t_bill',
            name='interest',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
