# Generated by Django 4.2 on 2023-06-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0050_alter_continent_continent'),
        ('rates', '0002_alter_t_bill_discount_alter_t_bill_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflation',
            name='country',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='international.country'),
        ),
    ]
