# Generated by Django 4.2 on 2023-06-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_t_bill_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mpr',
            name='country',
        ),
        migrations.RemoveField(
            model_name='t_bill',
            name='country',
        ),
    ]
