# Generated by Django 4.2 on 2023-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(default='sector.png', upload_to='topic')),
                ('slug', models.SlugField(default='A', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(default='sector.png', upload_to='topic')),
                ('slug', models.SlugField(default='financial', unique=True)),
            ],
        ),
    ]
