# Generated by Django 4.2 on 2023-06-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(default='sector.png', upload_to='term')),
                ('take_away', models.CharField(max_length=255, unique=True)),
                ('meaning', models.TextField(unique=True)),
                ('example', models.TextField(unique=True)),
                ('video_url', models.CharField(max_length=255, unique=True)),
                ('first_letter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_letter', to='education.topics')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='term', to='education.topics')),
            ],
        ),
    ]
