# Generated by Django 4.2 on 2023-06-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='first_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_letter', to='education.firstalphabet'),
        ),
    ]
