# Generated by Django 3.2.7 on 2021-09-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_type', models.CharField(choices=[('Precious Metals', 'Precious Metals'), ('Base Metals', 'Base Metals'), ('Energies', 'Energies'), ('Soft Commodities', 'Soft Commodities')], max_length=255)),
                ('slug', models.SlugField(default='soft', unique=True)),
                ('icon', models.ImageField(default='commodities.png', upload_to='commodity_type')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Americas', 'Americas'), ('Oceania', 'Oceania')], max_length=50)),
                ('slug', models.SlugField(default='Europe', unique=True)),
                ('icon', models.ImageField(default='globe.svg', upload_to='continent')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=2)),
                ('slug', models.SlugField(unique=True)),
                ('flag', models.ImageField(default='globe.svg', upload_to='country')),
                ('currency', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=3)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('component', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.country')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('slug', models.SlugField(default='soft', unique=True)),
                ('icon', models.ImageField(default='commodities.png', upload_to='commodity_type')),
                ('exchange', models.CharField(max_length=255)),
                ('contract_size', models.CharField(max_length=255)),
                ('point_size', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.commodity_type')),
            ],
        ),
    ]
