# Generated by Django 3.2.7 on 2021-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='time_zone',
            field=models.CharField(default='GMT+0', max_length=15),
        ),
    ]
