# Generated by Django 3.2.7 on 2021-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0003_auto_20211013_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area_size',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
