# Generated by Django 3.2.7 on 2021-10-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0004_country_area_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='Accra', max_length=255),
        ),
    ]
