# Generated by Django 3.2.7 on 2021-10-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0005_country_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(default='sector.png', upload_to='presidents')),
                ('url', models.CharField(max_length=255)),
                ('elected_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='international.country')),
            ],
        ),
    ]
