# Generated by Django 3.2.7 on 2021-10-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0008_alter_centralbank_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=8),
        ),
    ]
