# Generated by Django 3.2.7 on 2021-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0009_alter_country_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='president',
            name='active',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
