# Generated by Django 3.2.7 on 2021-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0010_president_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='active',
            field=models.CharField(choices=[('Active', 'Active'), ('Former', 'Former')], default='Active', max_length=10),
        ),
    ]
