# Generated by Django 3.2.7 on 2021-10-15 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0012_bankrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrate',
            name='effective_meeting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
