# Generated by Django 3.2.7 on 2021-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0013_bankrate_effective_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
