# Generated by Django 3.2.7 on 2021-10-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0015_auto_20211018_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_profile',
            name='point_size',
            field=models.CharField(max_length=900),
        ),
    ]
