# Generated by Django 3.2.7 on 2021-10-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0016_alter_commodity_profile_point_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
