# Generated by Django 3.2.7 on 2021-10-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0017_alter_indice_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='president',
            old_name='logo',
            new_name='picture',
        ),
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('commenced_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(default='sector.png', upload_to='bourse')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.country')),
            ],
        ),
        migrations.AddField(
            model_name='indice',
            name='main_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='international.bourse'),
        ),
    ]
