# Generated by Django 3.2.7 on 2021-10-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0019_bourse_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrate',
            name='realeased_file',
            field=models.FileField(blank=True, null=True, upload_to='base_rate'),
        ),
    ]
