# Generated by Django 3.2.7 on 2021-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0020_bankrate_realeased_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bourse',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
