# Generated by Django 3.2.7 on 2021-10-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0021_bourse_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorExports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export', models.CharField(max_length=255)),
                ('country', models.ManyToManyField(to='international.Country')),
            ],
        ),
    ]
