# Generated by Django 3.2.7 on 2021-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0022_majorexports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexports',
            name='export',
        ),
        migrations.AddField(
            model_name='majorexports',
            name='export',
            field=models.ManyToManyField(to='international.Commodity_profile'),
        ),
    ]
