# Generated by Django 3.2.7 on 2021-10-30 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0024_alter_majorexports_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexports',
            name='export',
        ),
        migrations.AddField(
            model_name='majorexports',
            name='export',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
