# Generated by Django 3.2.7 on 2021-10-30 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0026_auto_20211030_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexports',
            name='export',
        ),
        migrations.AddField(
            model_name='majorexports',
            name='export',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Crude', 'Crude'), ('Cocoa', 'Cocoa'), ('Coal', 'Coal'), ('Machinery', 'Machinery')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
