# Generated by Django 3.2.7 on 2021-11-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0030_gdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdp',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
