# Generated by Django 3.2.7 on 2021-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0031_alter_gdp_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralbank',
            name='country',
        ),
        migrations.AddField(
            model_name='centralbank',
            name='country',
            field=models.ManyToManyField(related_name='central_bank', to='international.Country'),
        ),
    ]
