# Generated by Django 4.0.5 on 2022-08-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0032_auto_20211105_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdp',
            options={'ordering': ('-value',)},
        ),
    ]
