# Generated by Django 4.2 on 2023-05-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0034_alter_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
    ]
