# Generated by Django 4.2 on 2023-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0035_remove_country_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralbank',
            name='dep_governor',
        ),
        migrations.RemoveField(
            model_name='centralbank',
            name='governor',
        ),
    ]
