# Generated by Django 4.2 on 2023-05-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0037_remove_country_flag_alter_continent_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='dialing_code',
            field=models.CharField(default='+233', max_length=15),
        ),
    ]
