# Generated by Django 4.2 on 2023-05-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0038_alter_country_dialing_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='time_zone',
            field=models.CharField(default='GMT+0', max_length=25),
        ),
    ]
