# Generated by Django 4.2 on 2023-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0039_alter_country_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='dialing_code',
            field=models.CharField(default='+233', max_length=25),
        ),
    ]
