# Generated by Django 4.2 on 2023-05-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0040_alter_country_dialing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='globe.svg', upload_to='country'),
        ),
    ]
