# Generated by Django 4.2 on 2023-05-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0041_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity_profile',
            name='icon',
        ),
    ]
