# Generated by Django 4.2 on 2023-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0042_remove_commodity_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_profile',
            name='icon',
            field=models.ImageField(default='commodities.png', upload_to='commodity_type'),
        ),
    ]
