# Generated by Django 4.2 on 2023-05-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0043_commodity_profile_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexports',
            name='export',
        ),
        migrations.AddField(
            model_name='majorexports',
            name='export',
            field=models.ManyToManyField(to='international.commodity_profile'),
        ),
    ]
