# Generated by Django 4.2 on 2023-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0044_remove_majorexports_export_majorexports_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexports',
            name='export',
        ),
        migrations.AddField(
            model_name='majorexports',
            name='export',
            field=models.CharField(choices=[('Base Metals', 'Base Metals'), ('Crude', 'Crude'), ('Cocoa', 'Cocoa'), ('Coal', 'Coal'), ('Banana', 'Banana'), ('Machinery', 'Machinery'), ('Machinery', 'Machinery')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
