# Generated by Django 4.2 on 2023-05-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0045_remove_majorexports_export_majorexports_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexports',
            name='country',
        ),
        migrations.RemoveField(
            model_name='majorexports',
            name='export',
        ),
        migrations.AddField(
            model_name='majorexports',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='international.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorexports',
            name='export',
            field=models.ManyToManyField(to='international.commodity_profile'),
        ),
    ]
