# Generated by Django 4.2 on 2023-05-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0046_remove_majorexports_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indice',
            name='component',
        ),
    ]
