# Generated by Django 4.2 on 2023-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0050_alter_continent_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Middle East', 'Middle East'), ('Asia', 'Asia'), ('Americas', 'Americas'), ('Oceania', 'Oceania')], max_length=50),
        ),
    ]
