# Generated by Django 4.2 on 2023-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0051_alter_continent_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Middle East and North Africa', 'Middle East and North Africa'), ('Asia', 'Asia'), ('Americas', 'Americas'), ('Oceania', 'Oceania')], max_length=50),
        ),
    ]
