# Generated by Django 4.2 on 2023-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
