# Generated by Django 4.2 on 2023-06-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_alter_profile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
